version: '3'
services:
    melon:
        entrypoint: /bin/sh
        build: 
            context: .
            dockerfile: ./Dockerfile
        image: melon-server:0.1
        networks:
            - db
        environment:
            - TZ=Korea
        ports:
            - "5080:80"
networks: 
    db: 